spring.application.name=sticky-notes-backend

# ===============================
# MongoDB Atlas Configuration
# ===============================

spring.data.mongodb.uri=mongodb+srv://stickynotes_admin:MduHQBkVW5iW5TGm@sticky-notes-cluster.zsvqe5c.mongodb.net/sticky_notes_db?appName=sticky-notes-cluster

# ===============================
# Server Configuration
# ===============================

server.port=8080